name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hello thanks for opening a issue, we welcome you to StacksAway."
        pr-message: "Thanks for opening your first Pull Request on StacksAway. Someone will review it soon!"
